version: "3"

services:
    nerf_ttt_api:
        build: .
        image: nerf_ttt_api
        container_name: nerf_ttt_api
        volumes:
            - ./src:/usr/src/app/src
        networks:
            - cluster
        tty: true

networks:
    cluster:
        external: true
